# Generated by Django 3.0.4 on 2020-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='databasestatewise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=200)),
                ('confirm_case', models.PositiveIntegerField(default=0)),
                ('cured', models.PositiveIntegerField(default=0)),
                ('death', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='databasetotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_affected', models.PositiveIntegerField(default=0)),
                ('total_cured', models.PositiveIntegerField(default=0)),
                ('total_died', models.PositiveIntegerField(default=0)),
                ('total_active', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
